name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_ENV: production

jobs:
  test:
    name: Run Linting and Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'release:')

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun runtime
        uses: oven-sh/setup-bun@v2

      - name: Install project dependencies
        run: bun install

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps

      - name: Run code linting
        run: bun run lint

      - name: Run unit test suite
        run: bun run test

      - name: Run e2e test suite
        run: bun run e2e

      - name: Build website static files
        run: bun run build:test-report

      - name: Upload static artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: website/static/playwright-report
          retention-days: 1

  release:
    name: Publish Package to NPM
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Bun runtime
        uses: oven-sh/setup-bun@v2

      - name: Install project dependencies
        run: bun install

      - name: Create and publish release
        run: bunx semantic-release

  website:
    name: Deploy Documentation to GitHub Pages
    needs: [test, release]
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    env:
      GIT_USER: thomas-jeanneau
      GIT_PASS: ${{ secrets.GH_TOKEN }}
      CURRENT_BRANCH: main
      GIT_USER_NAME: thomas-jeanneau
      GIT_USER_EMAIL: thomas.jeanneau@latechforce.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Bun runtime
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build website blog
        run: bun run build:blog

      - name: Build website guides
        run: bun run build:guides

      - name: Build website schema
        run: bun run build:schema

      - name: Download test-report artifacts
        uses: actions/download-artifact@v4
        with:
          name: test-report
          path: website/static/playwright-report

      - name: Install website dependencies
        run: cd website && bun install

      - name: Deploy to GitHub Pages
        run: cd website && bun run deploy

      - name: Configure Git
        run: |
          git config --global user.name "${{ env.GIT_USER_NAME }}"
          git config --global user.email "${{ env.GIT_USER_EMAIL }}"

      - name: Commit downloaded artifacts
        run: |
          git add website
          git commit -m "chore: update website from deployment [skip ci]" || echo "No changes to commit"
          git push origin main
